### ISSUE TITLE
Deva out of memory 

### ISSUE THREAD

**Issue by zhangzehao123** [lkeab/gaussian-grouping#10]
![image](https://github.com/lkeab/gaussian-grouping/assets/117174448/b8f79d5b-0d63-4a4f-8292-4d7bab01229c)
Hello, when I try to find the dynamic masks of the video,my gpu memory was run out, how can i solve it? I used 4070 GPU.

Thank you！

**Comment by txlu4** [comment]
Hello, I encountered the similar problem, do you have any suggestions to solve?
