### ISSUE TITLE
About the preparation of dataset

### ISSUE THREAD

**Issue by MADONOKOUKI** [lkeab/gaussian-grouping#2]
The [setup document ](https://github.com/lkeab/gaussian-grouping/blob/main/docs/train.md) explain that by preparing the dataest with following setup, we can execute the convert.py
```
<location>
|---input
    |---<image 0>
    |---<image 1>
    |---...
 ```
 However when execute the 
 ```
 python convert.py -s data/lerf/figurines
 ```
 It shows the following error, which means it failed at Feature extraction.
 ```
 >  python convert.py -s data/lerf/figurines
sh: 1: colmap: not found
ERROR:root:Feature extraction failed with code 32512. Exiting.
 ```
 
 Is there any way to execute convert.py with proper way?

**Comment by Yenhongxuan** [comment]
How did you solve this problem?

**Comment by MichaelWangGo** [comment]
How did you solve this problem?

**Comment by MichaelWangGo** [comment]
Did you solve this problem?
