### ISSUE TITLE
Inquiry about Semantic Category Retrieval Capability in the Model

### ISSUE THREAD

**Issue by linyanAI** [lkeab/gaussian-grouping#7]
Could you please provide information on whether the model is equipped to identify and classify semantic categories such as desk or table?  If yes, where it is.

**Comment by lkeab** [comment]
Yes, the provided 2D masks can be from Grounded-SAM, where each mask has category information. Or you can use Grounding DINO to pick the output masks of SAM inside the 2D bounding boxes. The 3D-2D mapping relation can lift this category information to 3D directly.

**Comment by linyanAI** [comment]
But the code now can not provide the corresponding category? Because I find the config just set the instance id to 256 rather than semantic id. Following the instruction, we can not directly acquire the semantic classes. Is this right?
